apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __CLAIM_NAME__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: __VOLUME_SIZE__
  storageClassName: slow
  volumeName: __VOLUME_NAME__