apiVersion: v1
kind: Service
metadata:
  name: __SERVICE_NAME__
  labels:
    app: __SERVICE_NAME__
spec:
  ports:
  - port: __SERVICE_PORT_HTTP__
    name: __SERVICE_NAME__-http
  ports:
  - port: __SERVICE_PORT_HTTPS__
    name: __SERVICE_NAME__-https
  clusterIP: None
  selector:
    app: __SERVICE_NAME__